### PR TITLE
Fix utilization of 'Combinations' in Task 5.

### PR DESCRIPTION
**Pull request by ingomueller-net**
See #1.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
@jpivarski: May I ask you to confirm whether #1 is indeed a bug and whether this PR fixes it? I am using the code in this repository to produce the reference results for the unit tests of our implementation, so I want to be sure, what is correct.

**Comment by jpivarski** [comment]
I'm not familiar enough with this example to say whether it's a bug. Have you asked [the author](https://github.com/stwunsch/opendata-benchmarks/blame/661aa662fe7b68854738bf44c01a2aa954cb376b/tasks/5/rdataframe.C), @stwunsch?

**Comment by ingomueller-net** [comment]
Yes, but he didn't react yet. Does anyone else come to you mind that I could ask?

**Comment by ingomueller-net** [comment]
I have modified this implementation as well as the one in [groot](https://github.com/go-hep/examples/blob/master/groot/bench-opendata/05-basic.go) to print the contents of the histograms. With my fix, the results are exactly the same (running on the first 100001 entries); without my fix, they are different.

@stwunsch Please let me know what you need to accept this MR.

**Comment by stwunsch** [comment]
Thanks! I'll pull this over to #4 because I'll add also the compiled versions.

**Pull request closed without merging**
